= goti_layout
Goti is a Bangla keyboard layout, inspired from Avro, Probhat and Boishakhi layout.

== Goals 

* স্বল্পব্যবহৃত বর্ণগুলো যথাসম্ভব মূল কোয়ার্টি সেকশনের বাইরে রাখা। কোনো কোনো স্বল্পব্যবহৃত বর্ণ alt মোডিফায়ারের সাহায্যে টাইপ করা। 
* কার চিহ্ন, ফলা চিহ্ন- শিফট বা অন্যকিছুর সহায়তা ছাড়াই এভেলেভল করা। কমা, ফুলস্টপ, প্রশ্নবোধক এইসব বোতামে কোনো অক্ষর না রাখা- যেহেতু এগুলো বহুল ব্যবহৃত। কার চিহ্নগুলোর বোতামে কোনো অক্ষর না রাখা, রাখলে ভুল কীপ্রেসের সম্ভাবনা বাড়ে।
* উপরোল্লিখিত কোনো নীতির জন্য দরকার না থাকলে _ফোনেটিকের নিয়ম ভঙ্গ না করা।_

গতি লেআউট অল্প কীপ্রেসে বাংলা লেখতে বানানো। যেসব বোতামের ক্ষেত্রে ভুল কীপ্রেস পড়ার সম্ভাবনা আছে সেগুলোকে আইসোলেট করার চেষ্টা করা হয়েছে। 
এছাড়াও কিছু বোতাম shift মোডিফায়ার চাপলেও তাদের আউটপুট একই ক্যারেক্টার রাখা হয়েছে ভুল কীপ্রেস সংশোধনের সময় কমানোর জন্য।
এমনকি বারবার বহুব্যবহৃত ক্যারেক্টার যেন খুঁজে সময় না নষ্ট করতে হয় সেজন্য alt+shift মোডিফায়ার ব্যবহার করা হয়েছে। 

== Setting Up

গতি লেআউট আপাতত শুধু লিনাক্স চালিত কম্পিউটারগুলোতে চলবে। ধীরে ধীরে অন্যান্য প্ল্যাটফর্মের জন্যও একে উন্মুক্ত করা হবে।
প্রথমেই দেখে নিন আপনার লিনাক্স ডিস্ট্রোটিতে `ibus, ibus-m17n` এ দুইটি প্যাকেজ ইন্সটল করা আছে কিনা। না থাকলে ইনস্টল করে নিন:

উবুন্টু বা, ডেবিয়ানভিত্তিক ডিস্ট্রো হলে-

`$ sudo apt install ibus ibus-m17n`

মাঞ্জারো বা আর্চভিত্তিক ডিস্ট্রো হলে-

`$ sudo pacman -S ibus ibus-m17n`

== After Install

```
$ git clone https://github.com/Emonshr/goti_layout.git
$ sudo cp goti_layout/bn-goti.mim /usr/share/m17n/
```
এরপর ibus থেকে preference>input method>Bengali>Bangla - goti (m17n) এভাবে গতি যুক্ত করে নিবেন।
এবার আপনার ডিস্ট্রো থেকে লগআউট করে আবার লগইন করুন। সবশেষে নিচের প্যানেলে লক্ষ্য করুন। ক্লিক করলে গতি কে পেয়ে যাবেন।

== Usage

মূল লেআউট দেখে নিন  https://github.com/Emonshr/goti_layout/blob/master/goti.png[এখানে]।

ফায়ারফক্স থেকে alt প্রেস করে টপবারের বদলে যুক্তবর্ণ লিখতে ব্রাউজার থেকে about:config এ যান এবং ui.key.menuAccessKeyFocuses = false করে দিন।


যুক্তবর্ণ তৈরি করতে হসন্ত(্) ব্যবহার করুন। যেমন: ম্প = m+h+p 

ষ লিখতে চাপুন alt+s

== Some other features

রেফ দিতে alt+z চাপুন, তারপর প্রয়োজনীয় অক্ষরটি চাপুন যার উপর রেফ দিতে চান।

ডট (.)  প্রশ্নবোধক(?) এসব লেআউট না পাল্টেই দেয়া যায় গতি লেআউটে।
প্রশ্নবোধক দিবেন shift+/ দিয়ে, ডট দিবেন shift+. চেপে।

== Experimental Features

এই যুক্তবর্ণগুলো পাওয়া যাবে alt+shift মোডিফায়ার/শর্টকাটে।

[cols=".<2,.^5"]
|===
|ঙ্গ  |alt+shift+M
|ক্ষ |alt+shift+K
|ঞ্জ |alt+shift+H
|জ্ঞ  |alt+shift+J
|ঞ্চ  |alt+shift+C
|জ্জ   |alt+shift+G
|ব্ব  |alt+shift+B
|ম্প  |alt+shift+V
|ত্ত  |alt+shift+F
|দ্ব  |alt+shift+Q
|দ্ধ  |alt+shift+W
|ভ্র  |alt+shift+X
|স্ট  |alt+shift+S
|ন্ঠ  |alt+shift+N
|ঙ্খ  |alt+shift+L
|ন্ত  |alt+shift+Z
|ক্ত  |alt+shift+D
|ত্ম  |alt+shift+A
|ট্ট  |alt+shift+T
|ষ্ট  |alt+shift+P
|ক্ষ্ণ  |alt+shift+O
|ত্ত্ব  |alt+shift+I
|ন্ত্র্য  |alt+shift+U
|ন্দ্র  |alt+shift+E
|হ্ম  |alt+shift+Y
|ন্ট্র  |alt+shift+R

|===

_পরীক্ষামূলক ফিচার হওয়ায় এই যুক্তবর্ণগুলো বা, এদের শর্টকাট যেকোনো সময় পরিবর্তিত হতে পারে।_
